// apps/front/todo-nuxtjs/src/components/Menu/Menu.vue
﻿<script setup lang="ts">
type Props = {
  userName: string;
  signOut: () => void;
  closeMenu: () => void;
};

defineProps<Props>();
</script>

<template>
  <div class="back-float">
    <div id="menu" class="menu">
      <div class="menu-title-box">
        <h1 id="user-name">{{ userName }}</h1>
      </div>
      <div class="menu-content-box">
        <div class="menu-content-list">
          <NuxtLink ref="/completed" :on-click="closeMenu">
            <h3>完了済TODO</h3>
          </NuxtLink>
        </div>
      </div>
      <div class="wrap-icon">
        <Icon
          name="PersonOff"
          :size="64"
          color="#FFFFFF"
          :click-icon="signOut"
        />
      </div>
    </div>
    <div id="outer-menu" class="outer-menu" :on-click="closeMenu"></div>
  </div>
</template>

<style lang="scss" scoped>
@import url('~/assets/css/animation.scss');

.back-float {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: flex-start;
  background-color: rgb(0 0 0 / 50%);

  > .menu {
    width: 300px;
    height: 100vh;
    display: flex;
    flex-direction: column;
    background-color: #4d4d4d;
    color: #fff;
    animation: slidein 0.3s ease-in;

    > .menu-title-box {
      width: 100%;
      height: 150px;
      display: flex;
      justify-content: center;
      align-items: center;
      border-bottom: 5px solid #fff;
    }

    > .menu-content-box {
      padding-top: 64px;
      flex-grow: 1;
      display: flex;
      flex-direction: column;
      align-self: center;
      gap: 24px;

      > .menu-content-list {
        list-style: none;
      }
    }

    > .wrap-icon {
      margin: 0 24px 24px 0;
      display: flex;
      flex-direction: row-reverse;
    }
  }

  > .outer-menu {
    flex-grow: 1;
  }
}
</style>

// apps/front/todo-nextjs/src/components/presentational/Menu/Menu.tsx
﻿'use client';

import Link from 'next/link';

import styled from 'styled-components';

import { slidein } from '~/libs/styledComponent';

import Icon from '~/components/container/Icon/Icon';

type Props = {
  userName: string;
  signOut: () => void;
  closeMenu: () => void;
};

const StyledBackFloat = styled.div`
  position: fixed;
  top: 0px;
  left: 0px;
  width: 100vw;
  height: 100vh;
  display: flex;
  justify-content: flex-start;
  background-color: rgba(0, 0, 0, 0.5);
`;
const StyledMenu = styled.div`
  width: 300px;
  height: 100vh;
  display: flex;
  flex-direction: column;
  background-color: #4d4d4d;
  color: #ffffff;

  animation: ${slidein} 0.3s ease-in;
`;
const StyledOuterMenu = styled.div`
  flex-grow: 1;
`;
const StyledMenuTitleBox = styled.div`
  width: 100%;
  height: 150px;
  display: flex;
  justify-content: center;
  align-items: center;
  border-bottom: 5px solid #ffffff;
`;
const StyledMenuContentBox = styled.div`
  padding-top: 64px;
  flex-grow: 1;
  display: flex;
  flex-direction: column;
  align-self: center;
  gap: 24px;
`;
const StyledMenuContentList = styled.li`
  list-style: none;
`;
const StyledWrapIcon = styled.div`
  margin: 0px 24px 24px 0px;
  display: flex;
  flex-direction: row-reverse;
`;

export default function Menu({ userName, signOut, closeMenu }: Props) {
  return (
    <StyledBackFloat>
      <StyledMenu test-id="menu-float">
        <StyledMenuTitleBox>
          <h1 id="user-name">{userName}</h1>
        </StyledMenuTitleBox>
        <StyledMenuContentBox>
          <StyledMenuContentList>
            <Link href={'/completed'} onClick={closeMenu}>
              <h3>完了済TODO</h3>
            </Link>
          </StyledMenuContentList>
        </StyledMenuContentBox>
        <StyledWrapIcon>
          <Icon
            presentational={{
              name: 'PersonOff',
              size: 64,
              color: '#FFFFFF',
            }}
            clickIcon={signOut}
          />
        </StyledWrapIcon>
      </StyledMenu>
      <StyledOuterMenu
        id="styled-outer-menu"
        onClick={closeMenu}
      ></StyledOuterMenu>
    </StyledBackFloat>
  );
}
