// apps/front/todo-nextjs/src/components/presentational/Form/TextArea.tsx
﻿'use client';

import { UseFormRegisterReturn } from 'react-hook-form';

type Props = {
  labelName: string;
  placeholder?: string;
  errorMessage: string | undefined;
  register: UseFormRegisterReturn | undefined;
};

export default function TextArea({
  labelName,
  placeholder,
  errorMessage,
  register,
}: Props) {
  return (
    <>
      <label htmlFor="textarea">{labelName}</label>
      <textarea
        id="textarea"
        rows={10}
        placeholder={placeholder}
        {...register}
      />
      <p id="textarea-error-message">{errorMessage}</p>
    </>
  );
}

// apps/front/todo-nuxtjs_v3/src/components/Form/TextArea.vue
﻿<script setup lang="ts">
type Props = {
  labelName: string;
  errorMessage: string | undefined;
  placeholder?: string;
};

defineProps<Props>();
</script>

<template>
  <div class="textarea">
    <label htmlFor="textarea">{{ labelName }}</label>
    <textarea id="textarea" :rows="10" :placeholder="placeholder" />
    <p id="textarea-error-message">{{ errorMessage }}</p>
  </div>
</template>

<style lang="scss" scoped>
.textarea {
  width: 100%;
  display: flex;
  flex-direction: column;

  label {
    display: block;
    margin-bottom: 6px;
  }

  textarea {
    width: 100%;
    box-sizing: border-box;
    border: 2px solid #000;
    padding: 8px 10px;
  }

  p {
    margin-left: 10px;
    color: #f00;
  }
}
</style>
