// apps/front/todo-nextjs/src/pages/completed/index.tsx
﻿import styled from 'styled-components';

import { wrapper } from '~/store/root';

import TodoEclipse from '~/components/container/Todo/TodoEclipse';
import TodoIconBox from '~/components/container/Todo/TodoIconBox';

import { STATUS } from '~/constants';

import {
  getRunningQueriesThunk,
  getTodos,
  useGetTodosQuery,
} from '~/services/todo';

import { dateFormat } from '~/utils/date';

const StyledTodoList = styled.div`
  display: flex;
  flex-direction: column;
  gap: 48px;
`;
const StyledTodo = styled.div`
  display: flex;
  flex-direction: column;
`;
const StyledTodoUnder = styled.div`
  margin-top: 8px;
  padding: 0 12px;
  display: flex;
  justify-content: space-between;
`;
const StyledTodoDeadlineAt = styled.p<{ color: string }>`
  color: ${({ color }) => color};
  font-weight: bold;
`;

export default function Completed() {
  const { data: todoList } = useGetTodosQuery(`${STATUS.DONE}`, {
    refetchOnMountOrArgChange: true,
  });

  const { formatToYYYYMMdd, colorizeDate } = dateFormat();

  return (
    <>
      <h1>完了済み</h1>
      <StyledTodoList>
        {todoList && todoList.length > 0
          ? todoList?.map((todo) => {
              return (
                <StyledTodo key={todo.id} id="todo">
                  <TodoEclipse
                    presentational={{
                      title: todo.title,
                      description: todo.description,
                    }}
                    id={String(todo.id)}
                    deadlineAt={todo.deadlineAt}
                  />
                  <StyledTodoUnder>
                    {todo.deadlineAt ? (
                      <StyledTodoDeadlineAt
                        color={colorizeDate(new Date(todo.deadlineAt))}
                        test-id="todo-deadline"
                      >
                        {formatToYYYYMMdd(new Date(todo.deadlineAt))}
                      </StyledTodoDeadlineAt>
                    ) : (
                      <p>{''}</p>
                    )}
                    <TodoIconBox
                      todoId={todo.id}
                      hasIcons={{ hasUncheck: true, hasTrashCan: true }}
                    />
                  </StyledTodoUnder>
                </StyledTodo>
              );
            })
          : []}
      </StyledTodoList>
    </>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    await store.dispatch(getTodos.initiate(`${STATUS.DONE}`));
    await Promise.all(store.dispatch(getRunningQueriesThunk()));

    return { props: '' };
  },
);

// apps/front/todo-nuxtjs/src/pages/completed.vue
﻿<script setup lang="ts">
const todoList = [
  {
    id: 1,
    userId: 1,
    title: 'title',
    description: 'description',
    deadlineAt: '2024-10-11',
    status: 'TODO',
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
];
</script>

<template>
  <div>
    <h1>完了済み</h1>
    <template v-if="todoList && todoList.length > 0">
      <div class="todo-list">
        <div v-for="todo in todoList" :key="todo.id" class="todo">
          <TodoEclipse
            :id="String(todo.id)"
            :title="todo.title"
            :description="todo.description"
            :click="() => {}"
          />
          <div class="todo-under">
            <div
              v-if="todo.deadlineAt"
              :id="`todo-deadline-${todo.id}`"
              class="todo-deadline-at"
              :style="{ color: colorizeDate(new Date(todo.deadlineAt)) }"
            >
              {{ formatToYyyyMMDd(new Date(todo.deadlineAt)) }}
            </div>
            <p v-else></p>
            <TodoIconBox
              :id="todo.id"
              :check="{ has: true, click: () => {} }"
              :trash-can="{ has: true, click: () => {} }"
            />
          </div>
        </div>
      </div>
    </template>
  </div>
</template>

<style lang="scss" scoped>
.todo-list {
  display: flex;
  flex-direction: column;
  gap: 48px;

  > .todo {
    display: flex;
    flex-direction: column;

    > .todo-under {
      margin-top: 8px;
      padding: 0 12px;
      display: flex;
      justify-content: space-between;

      > .todo-deadline-at {
        font-weight: bold;
      }
    }
  }
}
</style>
