// apps/front/todo-nextjs/src/pages/index.tsx
﻿import styled from 'styled-components';

import { wrapper } from '~/store/root';

import Icon from '~/components/container/Icon/Icon';
import TodoEclipse from '~/components/container/Todo/TodoEclipse';
import TodoIconBox from '~/components/container/Todo/TodoIconBox';

import { STATUS } from '~/constants';

import {
  getRunningQueriesThunk,
  getTodos,
  useGetTodosQuery,
} from '~/services/todo';

import { dateFormat } from '~/utils/date';

const StyledTodoList = styled.div`
  display: flex;
  flex-direction: column;
  gap: 48px;
`;
const StyledTodo = styled.div`
  display: flex;
  flex-direction: column;
`;
const StyledTodoUnder = styled.div`
  margin-top: 8px;
  padding: 0 12px;
  display: flex;
  justify-content: space-between;
`;
const StyledTodoDeadlineAt = styled.p<{ color: string }>`
  color: ${({ color }) => color};
  font-weight: bold;
`;
const StyledNotHave = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;

export default function Top() {
  const { data: todoList } = useGetTodosQuery(`${STATUS.TODO},${STATUS.WIP}`, {
    refetchOnMountOrArgChange: true,
  });

  const { formatToYYYYMMdd, colorizeDate } = dateFormat();

  return (
    <>
      {todoList ? (
        <StyledTodoList>
          {todoList.map((todo) => (
            <StyledTodo key={todo.id} id="todo">
              <TodoEclipse
                presentational={{
                  title: todo.title,
                  description: todo.description || '',
                }}
                id={String(todo.id)}
                deadlineAt={todo.deadlineAt}
              />
              <StyledTodoUnder>
                {todo.deadlineAt ? (
                  <StyledTodoDeadlineAt
                    test-id="todo-deadline"
                    color={colorizeDate(new Date(todo.deadlineAt))}
                  >
                    {formatToYYYYMMdd(new Date(todo.deadlineAt))}
                  </StyledTodoDeadlineAt>
                ) : (
                  <p>{''}</p>
                )}
                <TodoIconBox
                  todoId={todo.id}
                  hasIcons={{
                    hasCheck: true,
                    hasSquareEdit: true,
                    hasTrashCan: true,
                  }}
                  todoForm={todo}
                />
              </StyledTodoUnder>
            </StyledTodo>
          ))}
        </StyledTodoList>
      ) : (
        <StyledNotHave>
          <Icon presentational={{ name: 'Check', size: 64 }} />
          <h2>登録されたTODOはありません</h2>
        </StyledNotHave>
      )}
    </>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    await store.dispatch(getTodos.initiate(`${STATUS.TODO},${STATUS.WIP}`));
    await Promise.all(store.dispatch(getRunningQueriesThunk()));

    return { props: '' };
  },
);

// apps/front/todo-nuxtjs/src/pages/index.vue
<script setup lang="ts">
const {
  data: todoList,
  error,
  refresh: refreshTodoList,
} = await useApiClient('/todos', {
  method: 'get',
  query: {
    status: 'WIP,TODO',
  },
});

const { toggleDetail } = useModalStore();

if (error.value !== null) {
  createErrorPage(error.value);
}

const uncheck = {
  has: true,
  click: () => {},
};
const check = {
  has: true,
};
const squareEdit = {
  has: true,
};
const trashCan = {
  has: true,
};
</script>

<template>
  <div v-if="todoList" class="todo-list">
    <div
      v-for="todo in todoList"
      :id="String(todo.id)"
      :key="todo.id"
      class="todo"
    >
      <TodoEclipse
        :title="todo.title"
        :description="todo.description"
        :click="toggleDetail"
      />
      <div class="todo-under">
        <div
          v-if="todo.deadlineAt"
          :id="`todo-deadline-${todo.id}`"
          class="todo-deadline-at"
          :style="{ color: colorizeDate(new Date(todo.deadlineAt)) }"
        >
          {{ formatToYyyyMMDd(new Date(todo.deadlineAt)) }}
        </div>
        <p v-else>" "</p>
        <TodoIconBox
          :todo-id="todo.id"
          :uncheck="uncheck"
          :check="check"
          :square-edit="squareEdit"
          :trash-can="trashCan"
          :refresh="refreshTodoList"
        />
      </div>
    </div>
  </div>
  <div v-else class="no-have">
    <Icon name="Check" :size="64" />
    <h2>なし</h2>
  </div>
</template>

<style lang="scss" scoped>
.todo-list {
  display: flex;
  flex-direction: column;
  gap: 48px;

  > .todo {
    display: flex;
    flex-direction: column;

    > .todo-under {
      margin-top: 8px;
      padding: 0 12px;
      display: flex;
      justify-content: space-between;

      > .todo-deadline-at {
        font-weight: bold;
      }
    }
  }
}

.no-have {
  display: flex;
  flex-direction: column;
  align-items: center;
}
</style>
