// apps/front/todo-nextjs/src/pages/signin/index.tsx
﻿import { signIn } from 'next-auth/react';
import styled from 'styled-components';

import Button from '~/components/container/Button/Button';
import Icon from '~/components/container/Icon/Icon';

const StyledSignup = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;
const StyledWrapButton = styled.div`
  margin-top: 32px;
`;

export default function Signin() {
  return (
    <StyledSignup>
      <Icon presentational={{ name: 'UserCircle', size: 128 }} />
      <StyledWrapButton>
        <Button
          presentational={{ text: 'サインイン', width: 128 }}
          onClick={signIn}
        />
      </StyledWrapButton>
    </StyledSignup>
  );
}

// apps/front/todo-nuxtjs/src/pages/signin.vue
﻿<script setup lang="ts"></script>

<template>
  <div class="signin">
    <Icon name="UserCircle" :size="128" />
    <div class="wrap-button">
      <Button text="サインイン" :width="128" :on-click="() => {}" />
    </div>
  </div>
</template>

<style lang="scss" scoped>
.signin {
  display: flex;
  flex-direction: column;
  align-items: center;

  > .wrap-button {
    margin-top: 32px;
  }
}
</style>
