// apps/front/todo-nextjs/src/components/presentational/Modal/TodoEdit.tsx
﻿'use client';

import { FormState, UseFormRegister } from 'react-hook-form';
import styled from 'styled-components';

import { TodoForm } from '~/types/todo';

import Button from '~/components/container/Button/Button';
import Date from '~/components/container/Form/Date';
import Form from '~/components/container/Form/Form';
import TextArea from '~/components/container/Form/TextArea';
import TextForm from '~/components/container/Form/TextForm';
import Modal from '~/components/container/Modal/Modal';

type Props = {
  title: string;
  description: string | undefined;
  formState: FormState<TodoForm>;
  register: UseFormRegister<TodoForm>;
};

const StyledContent = styled.div`
  width: 100%;
  margin-bottom: 24px;

  > p {
    padding-left: 8px;
  }
`;
const StyledButtonBox = styled.div`
  width: 70%;
  margin: auto;
  display: flex;
  justify-content: center;
  flex-direction: column;
  gap: 24px;
`;

export default function TodoEdit({
  title,
  description,
  formState,
  register,
}: Props) {
  const { errors, isValid } = formState;
  return (
    <Modal>
      <>
        <h1>編集</h1>
        <Form submit={() => {}}>
          <>
            <StyledContent>
              <TextForm
                presentational={{
                  labelName: 'タイトル',
                  placeholder: title,
                  errorMessage: errors.title?.message,
                  register: register('title'),
                }}
              />
            </StyledContent>
            <StyledContent>
              <TextArea
                presentational={{
                  labelName: '説明',
                  placeholder: description,
                  errorMessage: errors.description?.message,
                  register: register('description'),
                }}
              />
            </StyledContent>
            <StyledContent>
              <Date
                presentational={{
                  labelName: '期限',
                  errorMessage: errors.deadlineAt?.message,
                  register: register('deadlineAt'),
                }}
              />
            </StyledContent>
            <StyledButtonBox>
              <Button presentational={{ text: '編集' }} disabled={!isValid} />
            </StyledButtonBox>
          </>
        </Form>
      </>
    </Modal>
  );
}

// apps/front/todo-nuxtjs/src/components/Modal/TodoEdit.vue
﻿<script setup lang="ts">
type Props = {
  todo: {
    title: string;
    description: string | undefined;
  };
  event: {
    onClickEdit: () => void;
  };
};

const { todo, event } = defineProps<Props>();
const { title, description } = todo;
const { onClickEdit } = event;
</script>

<template>
  <Modal>
    <h1>編集</h1>
    <Form :submit="() => {}">
      <TextForm
        class="content"
        label-name="タイトル"
        :placeholder="title"
        error-message="error"
      />
      <TextArea
        class="content"
        label-name="説明"
        :placeholder="description"
        error-message="error"
      />
      <Date class="content" label-name="期限" error-message="error" />
      <div class="button-box">
        <Button text="編集" :disabled="false" :on-click="onClickEdit" />
      </div>
    </Form>
  </Modal>
</template>

<style lang="scss" scoped>
.content {
  width: 100%;
  margin-bottom: 24px;

  > p {
    padding-left: 8px;
  }
}

.button-box {
  width: 70%;
  margin: auto;
  display: flex;
  justify-content: center;
  flex-direction: column;
  gap: 24px;
}
</style>
