// apps/front/todo-nextjs/src/components/presentational/Todo/TodoEclipse.tsx
﻿import styled from 'styled-components';

type Props = {
  title: string;
  description: string | undefined;
  click: () => void;
};

const StyledTodoEcipse = styled.div`
  padding: 24px 46px;
  border: 4px solid #8f8f8f;
  border-radius: 90px;
  cursor: pointer;
`;
const StyledTodoTitle = styled.h3`
  margin: 0px 0px 6px 0px;
  display: -webkit-box;
  overflow: hidden;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 1;
`;
const StyledTodoDescription = styled.p`
  margin: 0px;
  display: -webkit-box;
  overflow: hidden;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 2;
`;

export default function TodoEclipse({ title, description, click }: Props) {
  return (
    <StyledTodoEcipse onClick={click}>
      <StyledTodoTitle test-id="todo-title">{title}</StyledTodoTitle>
      <StyledTodoDescription test-id="todo-description">
        {description}
      </StyledTodoDescription>
    </StyledTodoEcipse>
  );
}

// apps/front/todo-nuxtjs_v3/src/components/Todo/TodoEclipse.vue
﻿<script setup lang="ts">
type Props = {
  title: string;
  description: string | undefined;
  click: () => void;
};

const { title, description, click } = defineProps<Props>();
</script>

<template>
  <div class="todo-eclipse" :onClick="click">
    <h3 id="todo-title" class="todo-title">{{ title }}</h3>
    <p id="todo-description" class="todo-description">{{ description }}</p>
  </div>
</template>

<style lang="scss" scoped>
.todo-eclipse {
  padding: 24px 46px;
  border: 4px solid #8f8f8f;
  border-radius: 90px;
  cursor: pointer;

  .todo-title {
    margin: 0 0 6px;
    display: -webkit-box;
    overflow: hidden;
    line-clamp: 1;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 1;
  }

  .todo-description {
    margin: 0;
    display: -webkit-box;
    overflow: hidden;
    line-clamp: 2;
    -webkit-box-orient: vertical;
    -webkit-line-clamp: 2;
  }
}
</style>
