// apps/front/todo-nextjs_page-router/src/components/presentational/Error/Error.tsx
﻿import { styled } from 'styled-components';

type Props = {
  displayed: boolean;
  text?: string;
};

const StyledErrorparagraph = styled.p`
  margin: 0px;
  padding: 24px 24px;
  background-color: pink;
  color: red;
`;

export default function Error({ displayed, text }: Props) {
  return displayed && <StyledErrorparagraph>{text}</StyledErrorparagraph>;
}

// apps/front/todo-nuxtjs/src/components/Error/Error.vue
﻿<script setup lang="ts">
type Props = {
  displayed: boolean;
  text?: string;
};

const { displayed, text } = defineProps<Props>();
</script>

<template>
  <p v-if="displayed" class="error-text">{{ text }}</p>
</template>

<style lang="scss" scoped>
.error-text {
  margin: 0;
  padding: 24px;
  background-color: pink;
  color: red;
}
</style>
