// apps/front/todo-nuxtjs/src/components/Form/TextForm.vue
﻿<script setup lang="ts">
type Props = {
  labelName: string;
  errorMessage: string | undefined;
  placeholder?: string;
};

defineProps<Props>();
</script>

<template>
  <div class="text">
    <label htmlFor="text">{{ labelName }}</label>
    <input id="textform" :placeholder="placeholder" />
    <p id="textform-error-message">{{ errorMessage }}</p>
  </div>
</template>

<style lang="scss" scoped>
.text {
  width: 100%;
  display: flex;
  flex-direction: column;

  label {
    display: block;
    margin-bottom: 6px;
  }

  input {
    width: 100%;
    box-sizing: border-box;
    border: 2px solid #000;
    padding: 8px 10px;
  }

  p {
    margin-left: 10px;
    color: #f00;
  }
}
</style>

// apps/front/todo-nextjs/src/components/presentational/Form/TextForm.tsx
﻿'use client';

import { UseFormRegisterReturn } from 'react-hook-form';
import styled from 'styled-components';

type Props = {
  labelName: string;
  errorMessage: string | undefined;
  register: UseFormRegisterReturn | undefined;
};

const StyledTextForm = styled.div`
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  gap: 6px;

  > input {
    width: 100%;
    border: 2px solid #000000;
    padding: 8px 10px;
  }

  > p {
    margin-left: 10px;
    color: #ff0000;
  }
`;

export default function TextForm({ labelName, errorMessage, register }: Props) {
  return (
    <StyledTextForm>
      <label>{labelName}</label>
      <input {...register}></input>
      <p>{errorMessage}</p>
    </StyledTextForm>
  );
}
