// apps/front/todo-nuxtjs/src/pages/signup.vue
﻿<script setup lang="ts">
// TODO サインアップ画面は、eメールとパスワードによる認証認可が実装されていないため
// TODO 一旦放置
</script>

<template>
  <div class="signup">
    <Icon name="UserCircle" :size="128" />
    <Form :submit="() => {}">
      <div class="input-form">
        <UserTextForm
          type="text"
          label-name="名前"
          error-message="エラーメッセージが表示されます"
        />
        <UserTextForm
          type="email"
          label-name="メールアドレス"
          error-message="エラーメッセージが表示されます"
        />
        <UserTextForm
          type="password"
          label-name="パスワード"
          error-message="エラーメッセージが表示されます"
        />
      </div>
      <div class="wrapped-button">
        <Button text="サインアップ" :width="128" :on-click="() => {}" />
      </div>
    </Form>
  </div>
</template>

<style lang="scss" scoped>
.signup {
  display: flex;
  flex-direction: column;
  align-items: center;

  > .input-form {
    margin-bottom: 46px;
    display: flex;
    flex-direction: column;
  }

  > .wrapped-button {
    margin: 0 auto;
  }
}
</style>

// apps/front/todo-nextjs/src/pages/signup/index.tsx
﻿import styled from 'styled-components';
import Button from '~/components/container/Button/Button';
import Form from '~/components/container/Form/Form';
import UserTextForm from '~/components/container/Form/UserTextForm';
import Icon from '~/components/container/Icon/Icon';

const StyledSignup = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
`;
const StyledInputForm = styled.div`
  margin-bottom: 46px;
  display: flex;
  flex-direction: column;
`;
const StyledWrapButton = styled.div`
  margin: 0 auto;
`;

export default function Signup() {
  return (
    <StyledSignup>
      <Icon presentational={{ name: 'UserCircle', size: 128 }} />
      <Form submit={() => {}}>
        <>
          <StyledInputForm>
            <UserTextForm
              type="text"
              presentational={{
                labelName: '名前',
                errorMessage: 'エラーメッセージが表示されます',
                register: undefined,
              }}
            />
            <UserTextForm
              type="email"
              presentational={{
                labelName: 'メールアドレス',
                errorMessage: 'エラーメッセージが表示されます',
                register: undefined,
              }}
            />
            <UserTextForm
              type="password"
              presentational={{
                labelName: 'パスワード',
                errorMessage: 'エラーメッセージが表示されます',
                register: undefined,
              }}
            />
          </StyledInputForm>
          <StyledWrapButton>
            <Button presentational={{ text: 'サインアップ', width: 128 }} />
          </StyledWrapButton>
        </>
      </Form>
    </StyledSignup>
  );
}
